# iamge: base on Dockerhub php image
# /var/www for volume becuase Dashboard need to move storage folder to it

version: '3.8'

services:
  opencart:
    image: websoft9dev/opencart:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
     - ${APP_HTTP_PORT}:80
    volumes:
      - opencart:/var/www
    restart: always

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    restart: always
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  opencart:
  mysql_data:
