version: '3.8'

services:
  opencart:
    image: docker.io/bitnami/opencart:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_PORT}:8080
    volumes:
      - opencart:/bitnami/opencart
    environment:
      - OPENCART_HOST=opencart
      - OPENCART_DATABASE_HOST=mysql
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=${DB_MYSQL_USER}
      - OPENCART_DATABASE_NAME=${DB_MYSQL_NAME}
      - OPENCART_DATABASE_PASSWORD=${DB_MYSQL_PASSWORD}
    links: 
      - mysql
    restart: always

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    restart: always
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

networks:
  default:
      name: ${APP_NAME}

volumes:
  opencart:
  mysql_data:
